language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install:
- gem install bundler:2.1.4
- nvm install --lts
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: bCA34FBaxi8yVkcWnEN082WJQSvEZfd7wucq2DsDLvaauedknswAeerG/2nEg8aSeaiS8dPwIpWpBMZF7mY7o2mzY2uvhYpT7rFmyZhoDxn8rcE4kFMwCTiMuIt+tXKt1Zn/8gdYO0AITjF8Y3LXU7+Pa0s0AjaMrxf36nzk0taxpPTlbjk2JOzz7oiEyrS6zRiqQ87MxYFI/JhS5nkC/SA0ekb9GeVAx8rqZOGrFsDkCZnYnqWGIDE/Jwm2N/XkYA9XfVxyoeboutbi1Oy1SSJJ1ddM3SHoVta7UzoUHgx8DcRuCWMKaFQJxmcWwduaI5cXPgB3ywD6E14VGA+Kk6hS3CCe2PfH7Ze3XhJ250ZB7ZiviQ4ncqfwDbmkQsLPtwTqqsyCkSk5z8WGRgSlscIOv6esFlQfQrGMmcO1KxA1rzsLjzonsgZHvqt40Z5VPHFR9SYHEP+HSSoIK/6UfZDtKFtSS6ATJgbuDytvMQcHXPN8bhKRJ6jix4aXFqs5D8q6YzVK/r7G5jGxIqSvmJW1lGpB3JqM6viVr5ds91QykNOIdczLuBF4KInC6b+aZlYwDaT6mO8Cw0wIMAVF9A48PieLTE/LDWM4DUnQtPHJJUlZMPI453/xGI8KssI2FuDZxrLpCHCImxVadAuVaVTM0LbXz/Y79bUtq+DsueE=
  app: reminder-time
  run: rails db:migrate
